site_name: FRDR Policies
site_url: http://127.0.0.1:8000/
plausible_domain: test.frdr.ca
theme:
    name: mkdocs
    custom_dir: 'frdr_theme'
nav:
    - English:
        - "Terms of Use": en/terms_of_use.md
        - "Privacy Policy": en/privacy.md
        - "Access and Reuse Policy": en/access_reuse.md
        - "Collections Development Policy": en/collections_development.md
        - "Data Retention and Deaccession Policy": en/data_retention.md
        - "Data Submission Policy": en/data_submission.md
        - "Metadata Harvesting Policy": en/metadata_harvesting.md
        - "Glossary of Terms": en/glossary.md
    - French:
        - "Conditions d'utilisation": fr/conditions_d'utilisation.md
        - "Politique de confidentialité": fr/confidentialité.md
        - "Politique en matière d’accès et de réutilisation": fr/accès_réutilisation.md
        - "Politique en matière de création de collections": fr/création_collections.md
        - "Politique en matière de rétention et de suppression des données": fr/rétention_des_données.md
        - "Politique en matière de soumission de données": fr/soumission_données.md
        - "Politique en matière de moissonnage de métadonnées": fr/moissonnage_métadonnées.md
        - "Glossaire terminologique": fr/glossaire.md

extra_css:
    - css/docs-theme.css
extra:
    repo_url: https://www.frdr-dfdr.ca/repo/
    prefix: "/"
    default_page_en: en/terms_of_use/
    default_page_fr: fr/conditions_d'utilisation/
    language_map:
        en:
            "Terms of Use": fr/conditions_d'utilisation/
            "Privacy Policy": fr/confidentialité/
            "Access and Reuse Policy": fr/accès_réutilisation/
            "Collections Development Policy": fr/création_collections/
            "Data Retention and Deaccession Policy": fr/rétention_des_données/
            "Data Submission Policy": fr/soumission_données/
            "Metadata Harvesting Policy": fr/moissonnage_métadonnées/
            "Glossary of Terms": fr/glossaire/
        fr:
            "Conditions d'utilisation": en/terms_of_use/
            "Politique de confidentialité": en/privacy/
            "Politique en matière d’accès et de réutilisation": en/access_reuse/
            "Politique en matière de création de collections": en/collections_development/
            "Politique en matière de rétention et de suppression des données": en/data_retention/
            "Politique en matière de soumission de données": en/data_submission/
            "Politique en matière de moissonnage de métadonnées": en/metadata_harvesting/
            "Glossaire terminologique": en/glossary/
