site_name: FRDR Policies
site_url: http://127.0.0.1:8000/
theme:
    name: mkdocs
    custom_dir: 'frdr_theme'
nav:
    - English:
        - "Terms of Use": en/terms_of_use.md
        - "Privacy Policy": en/privacy_policy.md
    - French:
        - "Conditions d'utilisation": fr/conditions_d'utilisation.md
        - "Politique de confidentialité": fr/politique_de_confidentialité.md

extra_css:
    - css/docs-theme.css
extra:
    repo_url: https://www.frdr-dfdr.ca/repo/
    prefix: "/"
    default_page_en: en/terms_of_use/
    default_page_fr: fr/conditions_d'utilisation/
    language_map:
        en:
            "Terms of Use": fr/conditions_d'utilisation.md
            "Privacy Policy": fr/politique_de_confidentialité.md
        fr:
            "Conditions d'utilisation": en/terms_of_use.md
            "Politique de confidentialité": en/privacy_policy.md
